task: detection

num_classes: 221
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /mnt/thanhpd/MTSD/mtsd_fully_annotated_train_images/images
    ann_file: /mnt/thanhpd/code/mtsd_cl/CL_rtdetr/train_output_file_coco.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /mnt/thanhpd/MTSD/mtsd_v2_fully_annotated_images.val.zip/images
    ann_file: /mnt/thanhpd/code/mtsd_cl/CL_rtdetr/val_output_file_coco.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False
